# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Maya_PY_Display_Color_Override_ui.ui'
#
# Created: Wed Jun 30 23:07:45 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(254, 398)
        MainWindow.setMaximumSize(QtCore.QSize(254, 398))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    \n"
"    \n"
"    color: rgb(80, 189, 148);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.color_6 = QtWidgets.QPushButton(self.centralwidget)
        self.color_6.setMinimumSize(QtCore.QSize(40, 40))
        self.color_6.setMaximumSize(QtCore.QSize(40, 40))
        self.color_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_6.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_6.setText("")
        self.color_6.setObjectName("color_6")
        self.gridLayout.addWidget(self.color_6, 2, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.color_12 = QtWidgets.QPushButton(self.centralwidget)
        self.color_12.setMinimumSize(QtCore.QSize(40, 40))
        self.color_12.setMaximumSize(QtCore.QSize(40, 40))
        self.color_12.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_12.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_12.setText("")
        self.color_12.setObjectName("color_12")
        self.gridLayout.addWidget(self.color_12, 3, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.color_13 = QtWidgets.QPushButton(self.centralwidget)
        self.color_13.setMinimumSize(QtCore.QSize(40, 40))
        self.color_13.setMaximumSize(QtCore.QSize(40, 40))
        self.color_13.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_13.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_13.setText("")
        self.color_13.setObjectName("color_13")
        self.gridLayout.addWidget(self.color_13, 4, 1, 1, 1)
        self.color_11 = QtWidgets.QPushButton(self.centralwidget)
        self.color_11.setMinimumSize(QtCore.QSize(40, 40))
        self.color_11.setMaximumSize(QtCore.QSize(40, 40))
        self.color_11.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_11.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_11.setText("")
        self.color_11.setObjectName("color_11")
        self.gridLayout.addWidget(self.color_11, 3, 4, 1, 1)
        self.color_4 = QtWidgets.QPushButton(self.centralwidget)
        self.color_4.setMinimumSize(QtCore.QSize(40, 40))
        self.color_4.setMaximumSize(QtCore.QSize(40, 40))
        self.color_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_4.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_4.setText("")
        self.color_4.setObjectName("color_4")
        self.gridLayout.addWidget(self.color_4, 2, 2, 1, 1)
        self.color_1 = QtWidgets.QPushButton(self.centralwidget)
        self.color_1.setMinimumSize(QtCore.QSize(40, 40))
        self.color_1.setMaximumSize(QtCore.QSize(40, 40))
        self.color_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_1.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_1.setText("")
        self.color_1.setObjectName("color_1")
        self.gridLayout.addWidget(self.color_1, 1, 4, 1, 1)
        self.color_5 = QtWidgets.QPushButton(self.centralwidget)
        self.color_5.setMinimumSize(QtCore.QSize(40, 40))
        self.color_5.setMaximumSize(QtCore.QSize(40, 40))
        self.color_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_5.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_5.setText("")
        self.color_5.setObjectName("color_5")
        self.gridLayout.addWidget(self.color_5, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 3)
        self.color_3 = QtWidgets.QPushButton(self.centralwidget)
        self.color_3.setMinimumSize(QtCore.QSize(40, 40))
        self.color_3.setMaximumSize(QtCore.QSize(40, 40))
        self.color_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_3.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_3.setText("")
        self.color_3.setObjectName("color_3")
        self.gridLayout.addWidget(self.color_3, 2, 1, 1, 1)
        self.color_7 = QtWidgets.QPushButton(self.centralwidget)
        self.color_7.setMinimumSize(QtCore.QSize(40, 40))
        self.color_7.setMaximumSize(QtCore.QSize(40, 40))
        self.color_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_7.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_7.setText("")
        self.color_7.setObjectName("color_7")
        self.gridLayout.addWidget(self.color_7, 2, 5, 1, 1)
        self.color_8 = QtWidgets.QPushButton(self.centralwidget)
        self.color_8.setMinimumSize(QtCore.QSize(40, 40))
        self.color_8.setMaximumSize(QtCore.QSize(40, 40))
        self.color_8.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_8.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_8.setText("")
        self.color_8.setObjectName("color_8")
        self.gridLayout.addWidget(self.color_8, 3, 1, 1, 1)
        self.color_9 = QtWidgets.QPushButton(self.centralwidget)
        self.color_9.setMinimumSize(QtCore.QSize(40, 40))
        self.color_9.setMaximumSize(QtCore.QSize(40, 40))
        self.color_9.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_9.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_9.setText("")
        self.color_9.setObjectName("color_9")
        self.gridLayout.addWidget(self.color_9, 3, 2, 1, 1)
        self.color_10 = QtWidgets.QPushButton(self.centralwidget)
        self.color_10.setMinimumSize(QtCore.QSize(40, 40))
        self.color_10.setMaximumSize(QtCore.QSize(40, 40))
        self.color_10.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_10.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_10.setText("")
        self.color_10.setObjectName("color_10")
        self.gridLayout.addWidget(self.color_10, 3, 3, 1, 1)
        self.color_19 = QtWidgets.QPushButton(self.centralwidget)
        self.color_19.setMinimumSize(QtCore.QSize(40, 40))
        self.color_19.setMaximumSize(QtCore.QSize(40, 40))
        self.color_19.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_19.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_19.setText("")
        self.color_19.setObjectName("color_19")
        self.gridLayout.addWidget(self.color_19, 5, 2, 1, 1)
        self.color_16 = QtWidgets.QPushButton(self.centralwidget)
        self.color_16.setMinimumSize(QtCore.QSize(40, 40))
        self.color_16.setMaximumSize(QtCore.QSize(40, 40))
        self.color_16.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_16.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_16.setText("")
        self.color_16.setObjectName("color_16")
        self.gridLayout.addWidget(self.color_16, 4, 4, 1, 1)
        self.color_20 = QtWidgets.QPushButton(self.centralwidget)
        self.color_20.setMinimumSize(QtCore.QSize(40, 40))
        self.color_20.setMaximumSize(QtCore.QSize(40, 40))
        self.color_20.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_20.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_20.setText("")
        self.color_20.setObjectName("color_20")
        self.gridLayout.addWidget(self.color_20, 5, 3, 1, 1)
        self.color_17 = QtWidgets.QPushButton(self.centralwidget)
        self.color_17.setMinimumSize(QtCore.QSize(40, 40))
        self.color_17.setMaximumSize(QtCore.QSize(40, 40))
        self.color_17.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_17.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_17.setText("")
        self.color_17.setObjectName("color_17")
        self.gridLayout.addWidget(self.color_17, 4, 5, 1, 1)
        self.color_14 = QtWidgets.QPushButton(self.centralwidget)
        self.color_14.setMinimumSize(QtCore.QSize(40, 40))
        self.color_14.setMaximumSize(QtCore.QSize(40, 40))
        self.color_14.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_14.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_14.setText("")
        self.color_14.setObjectName("color_14")
        self.gridLayout.addWidget(self.color_14, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 6, 1, 1)
        self.color_15 = QtWidgets.QPushButton(self.centralwidget)
        self.color_15.setMinimumSize(QtCore.QSize(40, 40))
        self.color_15.setMaximumSize(QtCore.QSize(40, 40))
        self.color_15.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_15.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_15.setText("")
        self.color_15.setObjectName("color_15")
        self.gridLayout.addWidget(self.color_15, 4, 3, 1, 1)
        self.color_18 = QtWidgets.QPushButton(self.centralwidget)
        self.color_18.setMinimumSize(QtCore.QSize(40, 40))
        self.color_18.setMaximumSize(QtCore.QSize(40, 40))
        self.color_18.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_18.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_18.setText("")
        self.color_18.setObjectName("color_18")
        self.gridLayout.addWidget(self.color_18, 5, 1, 1, 1)
        self.color_25 = QtWidgets.QPushButton(self.centralwidget)
        self.color_25.setMinimumSize(QtCore.QSize(40, 40))
        self.color_25.setMaximumSize(QtCore.QSize(40, 40))
        self.color_25.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_25.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_25.setText("")
        self.color_25.setObjectName("color_25")
        self.gridLayout.addWidget(self.color_25, 6, 3, 1, 1)
        self.color_22 = QtWidgets.QPushButton(self.centralwidget)
        self.color_22.setMinimumSize(QtCore.QSize(40, 40))
        self.color_22.setMaximumSize(QtCore.QSize(40, 40))
        self.color_22.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_22.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_22.setText("")
        self.color_22.setObjectName("color_22")
        self.gridLayout.addWidget(self.color_22, 5, 5, 1, 1)
        self.color_27 = QtWidgets.QPushButton(self.centralwidget)
        self.color_27.setMinimumSize(QtCore.QSize(40, 40))
        self.color_27.setMaximumSize(QtCore.QSize(40, 40))
        self.color_27.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_27.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_27.setText("")
        self.color_27.setObjectName("color_27")
        self.gridLayout.addWidget(self.color_27, 6, 5, 1, 1)
        self.color_29 = QtWidgets.QPushButton(self.centralwidget)
        self.color_29.setMinimumSize(QtCore.QSize(40, 40))
        self.color_29.setMaximumSize(QtCore.QSize(40, 40))
        self.color_29.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_29.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_29.setText("")
        self.color_29.setObjectName("color_29")
        self.gridLayout.addWidget(self.color_29, 7, 2, 1, 1)
        self.color_24 = QtWidgets.QPushButton(self.centralwidget)
        self.color_24.setMinimumSize(QtCore.QSize(40, 40))
        self.color_24.setMaximumSize(QtCore.QSize(40, 40))
        self.color_24.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_24.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_24.setText("")
        self.color_24.setObjectName("color_24")
        self.gridLayout.addWidget(self.color_24, 6, 2, 1, 1)
        self.color_31 = QtWidgets.QPushButton(self.centralwidget)
        self.color_31.setMinimumSize(QtCore.QSize(40, 40))
        self.color_31.setMaximumSize(QtCore.QSize(40, 40))
        self.color_31.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_31.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_31.setText("")
        self.color_31.setObjectName("color_31")
        self.gridLayout.addWidget(self.color_31, 7, 4, 1, 1)
        self.color_23 = QtWidgets.QPushButton(self.centralwidget)
        self.color_23.setMinimumSize(QtCore.QSize(40, 40))
        self.color_23.setMaximumSize(QtCore.QSize(40, 40))
        self.color_23.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_23.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_23.setText("")
        self.color_23.setObjectName("color_23")
        self.gridLayout.addWidget(self.color_23, 6, 1, 1, 1)
        self.color_30 = QtWidgets.QPushButton(self.centralwidget)
        self.color_30.setMinimumSize(QtCore.QSize(40, 40))
        self.color_30.setMaximumSize(QtCore.QSize(40, 40))
        self.color_30.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_30.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_30.setText("")
        self.color_30.setObjectName("color_30")
        self.gridLayout.addWidget(self.color_30, 7, 3, 1, 1)
        self.color_26 = QtWidgets.QPushButton(self.centralwidget)
        self.color_26.setMinimumSize(QtCore.QSize(40, 40))
        self.color_26.setMaximumSize(QtCore.QSize(40, 40))
        self.color_26.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_26.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_26.setText("")
        self.color_26.setObjectName("color_26")
        self.gridLayout.addWidget(self.color_26, 6, 4, 1, 1)
        self.color_28 = QtWidgets.QPushButton(self.centralwidget)
        self.color_28.setMinimumSize(QtCore.QSize(40, 40))
        self.color_28.setMaximumSize(QtCore.QSize(40, 40))
        self.color_28.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_28.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_28.setText("")
        self.color_28.setObjectName("color_28")
        self.gridLayout.addWidget(self.color_28, 7, 1, 1, 1)
        self.color_32 = QtWidgets.QPushButton(self.centralwidget)
        self.color_32.setMinimumSize(QtCore.QSize(40, 40))
        self.color_32.setMaximumSize(QtCore.QSize(40, 40))
        self.color_32.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_32.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_32.setText("")
        self.color_32.setObjectName("color_32")
        self.gridLayout.addWidget(self.color_32, 7, 5, 1, 1)
        self.color_21 = QtWidgets.QPushButton(self.centralwidget)
        self.color_21.setMinimumSize(QtCore.QSize(40, 40))
        self.color_21.setMaximumSize(QtCore.QSize(40, 40))
        self.color_21.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_21.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_21.setText("")
        self.color_21.setObjectName("color_21")
        self.gridLayout.addWidget(self.color_21, 5, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 1, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(75, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 8, 4, 1, 2)
        self.color_2 = QtWidgets.QPushButton(self.centralwidget)
        self.color_2.setMinimumSize(QtCore.QSize(40, 40))
        self.color_2.setMaximumSize(QtCore.QSize(40, 40))
        self.color_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.color_2.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.color_2.setText("")
        self.color_2.setObjectName("color_2")
        self.gridLayout.addWidget(self.color_2, 1, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Overrides color", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))

